web:
  build: ./python
  ports: 
    - "8082:8082"
  volumes:
    - ./python:/usr/src/app/python
  links:
    - redis
    - mysql
redis:
  image: redis
mysql:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./db:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=mysqldb
    - MYSQL_ROOT_PASSWORD=admin123
